// Warm-browser render microservice for GreenMentor aura headers.
//
// Why this exists: the header export is a real headless-Chromium screenshot of a
// live cross-origin WebGL aura iframe. On a Vercel serverless Lambda that meant
// paying chromium cold-start extraction on every invocation and rendering software
// WebGL under a hard maxDuration — which blew past the limit (FUNCTION_INVOCATION_
// TIMEOUT). Here we keep ONE Chromium warm across requests, use the full Playwright
// build (no @sparticuz/chromium, so none of its bin-tracing / version-mismatch
// pitfalls), and take as long as a render actually needs.
//
// Contract: POST /shot with the fully-formed header HTML; get back the encoded
// image. The header HTML is generated by community-engine (lib/header) and passed
// in verbatim, so this service owns zero product logic — it just drives a browser.

import http from "node:http";
import { chromium } from "playwright";
import sharp from "sharp";

const PORT = Number(process.env.PORT || 8080);
const SECRET = process.env.HEADER_RENDER_SECRET || "";
const CONCURRENCY = Math.max(1, Number(process.env.RENDER_CONCURRENCY || 3));
const MAX_BODY_BYTES = 8 * 1024 * 1024; // header HTML embeds data-URI logos; be generous.

if (!SECRET) {
  // Fail closed: without a shared secret the /shot endpoint rejects everything, so
  // an accidentally-public Fly URL can't be used to drive an arbitrary browser.
  console.warn("[render] HEADER_RENDER_SECRET is unset — /shot will reject all requests.");
}

// ---- warm browser -----------------------------------------------------------

let browserPromise = null;

/** A single Chromium reused across requests; relaunched if it dies. */
async function getBrowser() {
  if (browserPromise) {
    const b = await browserPromise.catch(() => null);
    if (b && b.isConnected()) return b;
    browserPromise = null;
  }
  browserPromise = chromium.launch({
    headless: true,
    // SwiftShader software WebGL: Fly machines are GPU-less, and the aura is WebGL.
    // Playwright's bundled Chromium renders black without an ANGLE/SwiftShader path.
    args: [
      "--use-gl=angle",
      "--use-angle=swiftshader",
      "--enable-unsafe-swiftshader",
      "--ignore-gpu-blocklist",
      "--no-sandbox",
      "--hide-scrollbars",
    ],
  });
  const b = await browserPromise;
  b.on("disconnected", () => {
    browserPromise = null;
  });
  return b;
}

// ---- concurrency limiter ----------------------------------------------------

let active = 0;
const waiters = [];
async function acquire() {
  if (active < CONCURRENCY) {
    active++;
    return;
  }
  await new Promise((resolve) => waiters.push(resolve));
  active++;
}
function release() {
  active--;
  const next = waiters.shift();
  if (next) next();
}

// ---- render -----------------------------------------------------------------

/**
 * @param {object} o
 * @param {string} o.html    Fully-formed header document HTML.
 * @param {number} o.width   CSS width.
 * @param {number} o.height  CSS height.
 * @param {number} [o.dpr]   Device pixel ratio (default 2).
 * @param {string} [o.selector]  Element to clip to (default "#header").
 * @param {number} [o.settleMs]  Aura warm-up before the shot (default 2600).
 * @param {"png"|"webp"} [o.format]  Encoded output (default "png").
 * @param {number} [o.quality]   WebP quality 1–100 (default 90).
 * @returns {Promise<Buffer>}
 */
async function render(o) {
  const {
    html,
    width,
    height,
    dpr = 2,
    selector = "#header",
    settleMs = 2600,
    format = "png",
    quality = 90,
  } = o;

  const t0 = Date.now();
  const mark = (phase) => console.log(`[render] ${phase} +${Date.now() - t0}ms`);

  const browser = await getBrowser();
  const page = await browser.newPage({
    // deviceScaleFactor is a top-level newPage option — nesting it inside `viewport`
    // silently drops it (DSF falls back to 1, halving the export resolution).
    viewport: { width, height },
    deviceScaleFactor: dpr,
  });
  try {
    // "load" (not "networkidle"): the aura iframe animates forever, so we rely on
    // the explicit settle rather than waiting for the network to go quiet.
    await page.setContent(html, { waitUntil: "load", timeout: 30_000 });
    mark("content-loaded");

    // Cap the webfont wait: fonts.ready can stay pending forever if a font stalls.
    await Promise.race([
      page.evaluate(() => document.fonts.ready),
      page.waitForTimeout(5_000),
    ]).catch(() => {});
    mark("fonts-ready");

    await page.waitForTimeout(settleMs);
    mark("settled");

    const el = await page.$(selector);
    const png = el
      ? await el.screenshot({ type: "png" })
      : await page.screenshot({ type: "png" });
    mark("screenshot");

    if (format === "webp") {
      const webp = await sharp(png).webp({ quality }).toBuffer();
      mark("encoded-webp");
      return webp;
    }
    return png;
  } finally {
    await page.close().catch(() => {});
  }
}

// ---- http -------------------------------------------------------------------

function readBody(req) {
  return new Promise((resolve, reject) => {
    let size = 0;
    const chunks = [];
    req.on("data", (c) => {
      size += c.length;
      if (size > MAX_BODY_BYTES) {
        reject(new Error("payload too large"));
        req.destroy();
        return;
      }
      chunks.push(c);
    });
    req.on("end", () => resolve(Buffer.concat(chunks)));
    req.on("error", reject);
  });
}

const server = http.createServer(async (req, res) => {
  if (req.method === "GET" && req.url === "/health") {
    res.writeHead(200, { "content-type": "text/plain" });
    res.end("ok");
    return;
  }

  if (req.method !== "POST" || (req.url || "").split("?")[0] !== "/shot") {
    res.writeHead(404, { "content-type": "text/plain" });
    res.end("not found");
    return;
  }

  // Constant-work auth: reject unless the shared secret matches.
  if (!SECRET || req.headers["x-render-secret"] !== SECRET) {
    res.writeHead(401, { "content-type": "text/plain" });
    res.end("unauthorized");
    return;
  }

  let body;
  try {
    const raw = await readBody(req);
    body = JSON.parse(raw.toString("utf8"));
  } catch (e) {
    res.writeHead(400, { "content-type": "text/plain" });
    res.end(`bad request: ${e.message}`);
    return;
  }

  if (!body?.html || !body?.width || !body?.height) {
    res.writeHead(400, { "content-type": "text/plain" });
    res.end("html, width and height are required");
    return;
  }

  const format = body.format === "webp" ? "webp" : "png";
  await acquire();
  try {
    const buf = await render({ ...body, format });
    res.writeHead(200, {
      "content-type": format === "webp" ? "image/webp" : "image/png",
      "content-length": buf.length,
      "cache-control": "no-store",
    });
    res.end(buf);
  } catch (e) {
    console.error("[render] failed:", e?.message);
    res.writeHead(500, { "content-type": "text/plain" });
    res.end(`render failed: ${e?.message ?? "unknown"}`);
  } finally {
    release();
  }
});

server.listen(PORT, () => {
  console.log(`[render] listening on :${PORT} (concurrency=${CONCURRENCY})`);
  // Warm the browser at boot so the first real request doesn't pay launch cost.
  getBrowser().then(
    () => console.log("[render] browser warm"),
    (e) => console.error("[render] warm-up failed:", e?.message)
  );
});

// Graceful shutdown so Fly rollouts don't drop in-flight renders.
for (const sig of ["SIGTERM", "SIGINT"]) {
  process.on(sig, () => {
    console.log(`[render] ${sig} — shutting down`);
    server.close(async () => {
      const b = await browserPromise?.catch(() => null);
      await b?.close().catch(() => {});
      process.exit(0);
    });
  });
}
