/**
 * Generate the marketing site's committed copy of the course catalog.
 *
 *   node --env-file=.env.local --import tsx scripts/gen-course-catalog.ts [--check] [--from-csv]
 *
 * academy/green-mentor-plus has no Supabase client and no Supabase env vars, and
 * it is mid-strangle into @gm/platform — adding a runtime dependency and two new
 * secrets to a shrinking app to render data that changes quarterly is a bad
 * trade. So it gets a generated file instead, read here through the anon key
 * against the same public view the platform renders at runtime.
 *
 * --check regenerates in memory and diffs against what's on disk, exiting
 * non-zero on drift. That is the guard against the usual failure mode of
 * generated files: silently going stale after someone re-runs catalog:import.
 *
 * --from-csv skips Supabase and emits straight from the committed intake sheet,
 * through the same normalisation the importer uses. Use it before 0027 is
 * applied, and in CI, where there are no Supabase credentials.
 *
 * Run after `catalog:import`.
 */
import { parseArgs } from "node:util";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, relative, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";
import { parseIntakeSheet } from "../lib/academy/catalog-intake";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, "../../../academy/green-mentor-plus/lib/data/courses.generated.ts");
const CSV = resolve(HERE, "./data/course-catalog.csv");

// One string literal, not a concatenation — see lib/academy/catalog.ts.
const COLUMNS =
  "slug, delivery, hosted_on, title, framework, level, description, outcome, module_count, lesson_count, duration_label, price_inr, included_in_plus, course_url, next_cohort_at, next_cohort_label, instructors, cover_image_url, position";

type Row = Record<string, unknown>;

function emit(rows: Row[]): string {
  const courses = rows.map((r) => ({
    slug: r.slug,
    delivery: r.delivery,
    hostedOn: r.hosted_on,
    title: r.title,
    framework: r.framework,
    level: r.level,
    description: r.description ?? "",
    outcome: r.outcome ?? "",
    moduleCount: r.module_count ?? null,
    lessonCount: r.lesson_count ?? null,
    durationLabel: r.duration_label ?? null,
    priceInr: r.price_inr ?? null,
    includedInPlus: r.included_in_plus,
    courseUrl: r.course_url,
    nextCohortAt: r.next_cohort_at ?? null,
    nextCohortLabel: r.next_cohort_label ?? null,
    instructors: r.instructors ?? [],
    coverImageUrl: r.cover_image_url ?? null,
    position: r.position,
  }));

  return `// GENERATED by @gm/platform \`catalog:gen\` — do not edit.
// Source of truth is public.course_catalog in Supabase, loaded from
// green-mentor-pro/platform/scripts/data/course-catalog.csv by \`catalog:import\`.
// Regenerate with: pnpm --filter @gm/platform catalog:gen
// CI runs \`catalog:gen -- --check\`, which fails if this file has drifted.

export type CatalogCourse = {
  slug: string;
  delivery: "self_paced" | "live";
  hostedOn: "in_app" | "learnyst";
  title: string;
  framework: string;
  level: "beginner" | "foundation" | "intermediate" | "advanced";
  description: string;
  outcome: string;
  moduleCount: number | null;
  lessonCount: number | null;
  /** Verbatim display string — "~67 min", "9.5 hours", "4 days". */
  durationLabel: string | null;
  /** Standalone INR list price. 0 = free, null = not sold standalone. */
  priceInr: number | null;
  includedInPlus: boolean;
  /** Absolute Learnyst URL, or an internal path when hostedOn is "in_app". */
  courseUrl: string;
  nextCohortAt: string | null;
  nextCohortLabel: string | null;
  instructors: string[];
  coverImageUrl: string | null;
  position: number;
};

export const courses: CatalogCourse[] = ${JSON.stringify(courses, null, 2)};
`;
}

async function main() {
  const args = process.argv.slice(2);
  if (args[0] === "--") args.shift();
  const { values } = parseArgs({
    args,
    options: { check: { type: "boolean", default: false }, "from-csv": { type: "boolean", default: false } },
  });

  let rows: Row[];
  if (values["from-csv"]) {
    // Offline path: emit straight from the committed sheet. Shares the same
    // normalisation as the importer, so this produces byte-identical output to
    // the DB path as long as the DB was imported from this sheet. Useful before
    // 0027 is applied, and in CI where there are no Supabase creds.
    const parsed = parseIntakeSheet(await readFile(CSV, "utf8"));
    rows = parsed.rows.filter((r) => r.status === "published") as unknown as Row[];
  } else {
    const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
    if (!url || !key) {
      throw new Error("catalog:gen needs NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY (or pass --from-csv)");
    }
    // Anon on purpose: this proves the same read the logged-out landing page does.
    const supabase = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
    const { data, error } = await supabase
      .from("course_catalog_public")
      .select(COLUMNS)
      .order("position", { ascending: true });
    if (error) throw new Error(`could not read course_catalog_public as anon: ${error.message}`);
    if (!data?.length) throw new Error("course_catalog_public returned no rows — run catalog:import first");
    rows = data as Row[];
  }

  const next = emit(rows);
  const rel = relative(process.cwd(), OUT);

  if (values.check) {
    const current = await readFile(OUT, "utf8").catch(() => null);
    if (current === next) {
      console.log(`✓ ${rel} is up to date (${rows.length} courses)`);
      return;
    }
    console.error(`✗ ${rel} is stale — run "pnpm --filter @gm/platform catalog:gen" and commit the result`);
    process.exit(1);
  }

  await writeFile(OUT, next, "utf8");
  console.log(`✓ wrote ${rel} — ${rows.length} courses`);
}

main().catch((e) => {
  console.error("catalog gen failed:", e instanceof Error ? e.message : e);
  process.exit(1);
});
