/**
 * Generate lib/msci/materiality-data.ts from an authenticated MSCI capture.
 *
 *   node --import tsx scripts/gen-msci-data.ts [--in=scripts/.out/msci-raw.json]
 *
 * Reads the raw portlet globals captured by extract-msci-materiality.ts and
 * emits the committed, typed dataset (taxonomy + per-industry weight matrix).
 * Deterministic: same capture → same file. This is the "transcribe" half of the
 * annual refresh — run it after `msci:extract`. Output is PROPRIETARY MSCI
 * reference data for INTERNAL USE ONLY (see the emitted header).
 */
import { parseArgs } from "node:util";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, "../lib/msci/materiality-data.ts");

type RawIssue = { name: string; description?: string };
type RawTheme = { name: string; classification: string; issues: RawIssue[] };
type RawIndustry = { name: string; data: number[]; gics?: string };
type Raw = {
  source?: string;
  themes: RawTheme[];
  sectorData: Record<string, RawIndustry>;
  subsectorData: Record<string, RawIndustry>;
  relevance: Record<string, RawIndustry>;
};

const PILLAR: Record<string, "environmental" | "social" | "governance"> = {
  Environment: "environmental",
  Social: "social",
  Governance: "governance",
};

/** "Biodiversity & Land Use" → "biodiversity-land-use" (matches lib/msci/materiality-map.ts). */
function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/&/g, " ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function j(v: unknown): string {
  return JSON.stringify(v);
}

async function main() {
  const { values } = parseArgs({
    args: process.argv.slice(2),
    options: { in: { type: "string", default: "scripts/.out/msci-raw.json" } },
  });
  const raw: Raw = JSON.parse(await readFile(values.in!, "utf8"));

  // Flatten themes in render order → the flat issue index used to key every data[] array.
  const flat: { id: string; name: string; description: string; pillar: string; theme: string }[] = [];
  for (const t of raw.themes) {
    const pillar = PILLAR[t.classification];
    if (!pillar) throw new Error(`unknown pillar classification: ${t.classification}`);
    for (const iss of t.issues) {
      flat.push({
        id: slugify(iss.name),
        name: iss.name,
        description: (iss.description ?? "").trim(),
        pillar,
        theme: t.name,
      });
    }
  }

  const width = new Set(Object.values(raw.subsectorData).map((s) => s.data.length));
  if (width.size !== 1) throw new Error(`ragged weight arrays: widths ${[...width]}`);
  const cols = [...width][0]; // 28 — the number of weighted columns
  const issues = flat.map((f, i) => ({ ...f, weightIndex: i < cols ? i : null }));
  const ids = issues.map((i) => i.id);
  if (new Set(ids).size !== ids.length) throw new Error("duplicate issue slug ids");

  const weightedOrder = issues.filter((i) => i.weightIndex !== null).map((i) => i.id);

  // Sectors (2-digit GICS) and sub-industries (8-digit) → compact tuples.
  const sectors = Object.entries(raw.sectorData).map(
    ([gics, s]) => [gics, s.name, s.data] as const,
  );
  const subs = Object.entries(raw.subsectorData).map(([gics, s]) => {
    const rel = raw.relevance[gics]?.data ?? [];
    return [gics, s.name, gics.slice(0, 2), s.data, rel] as const;
  });

  const asOf = "February 11, 2026"; // MSCI's stated "Average Key Issue weights calculated as of" date

  const body = `/**
 * GENERATED by scripts/gen-msci-data.ts — DO NOT EDIT BY HAND.
 * Regenerate: pnpm --filter @gm/platform msci:extract && pnpm --filter @gm/platform msci:gen
 *
 * ─── PROPRIETARY MSCI REFERENCE DATA — INTERNAL USE ONLY ──────────────────────
 * MSCI ESG Industry Materiality Map — the taxonomy plus the per-industry average
 * Key Issue weight matrix, captured from the (login-gated) MSCI portlet.
 * NOT for public display or redistribution. GICS® is jointly owned by MSCI & S&P.
 *
 * Source: ${raw.source ?? "MSCI ESG Industry Materiality Map"}
 * Average Key Issue weights calculated as of ${asOf}.
 *
 * Shape: each industry's \`weights\` is a ${cols}-number array of average Key Issue
 * weights (%), aligned position-by-position to WEIGHTED_ISSUE_ORDER (13
 * Environmental + 14 Social Key Issues, then 1 combined Governance weight at the
 * final index). Per-industry weights sum to ~100. The 6 Governance sub-issues
 * (Ownership & Control, Board, Pay, Accounting, Business Ethics, Tax
 * Transparency) are published for context but carry no separate weight
 * (weightIndex null) — Governance is weighted once at the pillar level.
 *
 * Sub-industry \`relevance\`: 1 = the Key Issue applies to ALL companies in the
 * industry; 0 = company-specific (MSCI shows a "CS" marker) when still weighted.
 */

export type MsciPillar = "environmental" | "social" | "governance";

/** [id, name, description, pillar, theme, weightIndex] */
export type RawIssueTuple = readonly [string, string, string, MsciPillar, string, number | null];

/** [gicsCode, name, weights] */
export type RawSectorTuple = readonly [string, string, readonly number[]];

/** [gicsCode, name, sectorCode, weights, relevance] */
export type RawSubIndustryTuple = readonly [string, string, string, readonly number[], readonly number[]];

export const MSCI_AS_OF = ${j(asOf)} as const;

/** Number of weighted Key Issue columns in every \`weights\`/\`relevance\` array. */
export const MSCI_WEIGHT_COLUMNS = ${cols} as const;

/** All ${issues.length} Key Issue rows, in MSCI's render order (index = flat issue index). */
export const MSCI_ISSUES_RAW: readonly RawIssueTuple[] = [
${issues.map((i) => `  [${j(i.id)}, ${j(i.name)}, ${j(i.description)}, ${j(i.pillar)}, ${j(i.theme)}, ${i.weightIndex === null ? "null" : i.weightIndex}],`).join("\n")}
];

/** The ${weightedOrder.length} weighted Key Issue ids, position-aligned to every \`weights\` array. */
export const WEIGHTED_ISSUE_ORDER: readonly string[] = [
${weightedOrder.map((id) => `  ${j(id)},`).join("\n")}
];

/** ${sectors.length} GICS sectors → average Key Issue weights. */
export const MSCI_SECTORS_RAW: readonly RawSectorTuple[] = [
${sectors.map(([g, n, d]) => `  [${j(g)}, ${j(n)}, [${d.join(",")}]],`).join("\n")}
];

/** ${subs.length} GICS sub-industries → average Key Issue weights + relevance flags. */
export const MSCI_SUBINDUSTRIES_RAW: readonly RawSubIndustryTuple[] = [
${subs.map(([g, n, s, d, r]) => `  [${j(g)}, ${j(n)}, ${j(s)}, [${d.join(",")}], [${(r as readonly number[]).join(",")}]],`).join("\n")}
];
`;

  await writeFile(OUT, body);
  console.log(
    `✓ wrote ${OUT}\n  ${issues.length} issues (${weightedOrder.length} weighted) · ` +
      `${sectors.length} sectors · ${subs.length} sub-industries`,
  );
}

main().catch((e) => {
  console.error("gen-msci-data failed:", e instanceof Error ? e.message : e);
  process.exit(1);
});
