/**
 * Generate the marketing site's committed copy of the course catalog.
 *
 *   node --env-file=.env.local --import tsx scripts/gen-course-catalog.ts [--check] [--from-csv]
 *
 * academy/green-mentor-plus has no Supabase client and no Supabase env vars, and
 * it is mid-strangle into @gm/platform — adding a runtime dependency and two new
 * secrets to a shrinking app to render data that changes quarterly is a bad
 * trade. So it gets a generated file instead, read here through the anon key
 * against the same public view the platform renders at runtime.
 *
 * --check regenerates in memory and diffs against what's on disk, exiting
 * non-zero on drift. That is the guard against the usual failure mode of
 * generated files: silently going stale after someone re-runs catalog:import.
 *
 * --from-csv skips Supabase and emits straight from the committed intake sheet,
 * through the same normalisation the importer uses. Use it before 0027 is
 * applied, and in CI, where there are no Supabase credentials.
 *
 * Run after `catalog:import`.
 */
import { parseArgs } from "node:util";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, relative, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";
import { parseIntakeSheet } from "../lib/academy/catalog-intake";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, "../../../academy/green-mentor-plus/lib/data/courses.generated.ts");
const CSV = resolve(HERE, "./data/course-catalog.csv");

// One string literal, not a concatenation — see lib/academy/catalog.ts.
const COLUMNS =
  "slug, kind, delivery, hosted_on, title, framework, level, description, outcome, module_count, lesson_count, course_count, duration_label, price_inr, included_in_plus, course_url, next_cohort_at, next_cohort_label, instructors, cover_image_url, position";

type Row = Record<string, unknown>;
type Link = { bundle_slug: string; course_slug: string; position: number };

function emit(rows: Row[], links: Link[]): string {
  const courses = rows
    .filter((r) => r.kind !== "bundle")
    .map((r) => ({
      slug: r.slug,
      delivery: r.delivery,
      hostedOn: r.hosted_on,
      title: r.title,
      framework: r.framework ?? "",
      level: r.level,
      description: r.description ?? "",
      outcome: r.outcome ?? "",
      moduleCount: r.module_count ?? null,
      lessonCount: r.lesson_count ?? null,
      durationLabel: r.duration_label ?? null,
      priceInr: r.price_inr ?? null,
      includedInPlus: r.included_in_plus,
      courseUrl: r.course_url,
      nextCohortAt: r.next_cohort_at ?? null,
      nextCohortLabel: r.next_cohort_label ?? null,
      instructors: r.instructors ?? [],
      coverImageUrl: r.cover_image_url ?? null,
      position: r.position,
    }));

  const bySlug = new Map(courses.map((c) => [c.slug, c]));
  const bundles = rows
    .filter((r) => r.kind === "bundle")
    .map((r) => ({
      slug: r.slug,
      title: r.title,
      level: r.level,
      description: r.description ?? "",
      outcome: r.outcome ?? "",
      courseCount: r.course_count ?? null,
      lessonCount: r.lesson_count ?? null,
      durationLabel: r.duration_label ?? null,
      priceInr: r.price_inr ?? null,
      courseUrl: r.course_url,
      coverImageUrl: r.cover_image_url ?? null,
      position: r.position,
      courses: links
        .filter((l) => l.bundle_slug === r.slug)
        .sort((a, b) => a.position - b.position)
        .map((l) => bySlug.get(l.course_slug))
        .filter(Boolean),
    }));

  return `// GENERATED by @gm/platform \`catalog:gen\` — do not edit.
// Source of truth is public.course_catalog in Supabase, loaded from
// green-mentor-pro/platform/scripts/data/course-catalog.csv by \`catalog:import\`.
// Regenerate with: pnpm --filter @gm/platform catalog:gen
// CI runs \`catalog:gen -- --check\`, which fails if this file has drifted.

export type CatalogCourse = {
  slug: string;
  delivery: "self_paced" | "live";
  hostedOn: "in_app" | "learnyst";
  title: string;
  framework: string;
  level: "beginner" | "foundation" | "intermediate" | "advanced";
  description: string;
  outcome: string;
  moduleCount: number | null;
  lessonCount: number | null;
  /** Verbatim display string — "~67 min", "9.5 hours", "4 days". */
  durationLabel: string | null;
  /** Standalone INR list price. 0 = free, null = not sold standalone. */
  priceInr: number | null;
  includedInPlus: boolean;
  /** Absolute Learnyst URL, or an internal path when hostedOn is "in_app". */
  courseUrl: string;
  nextCohortAt: string | null;
  nextCohortLabel: string | null;
  instructors: string[];
  coverImageUrl: string | null;
  position: number;
};

export type CatalogBundle = {
  slug: string;
  title: string;
  level: "beginner" | "foundation" | "intermediate" | "advanced";
  description: string;
  outcome: string;
  /** How many courses the bundle advertises — may exceed \`courses.length\`. */
  courseCount: number | null;
  lessonCount: number | null;
  durationLabel: string | null;
  priceInr: number | null;
  courseUrl: string;
  coverImageUrl: string | null;
  position: number;
  /** Resolved members, in sheet order. Empty when not yet listed. */
  courses: CatalogCourse[];
};

export const courses: CatalogCourse[] = ${JSON.stringify(courses, null, 2)};

export const bundles: CatalogBundle[] = ${JSON.stringify(bundles, null, 2)};
`;
}

async function main() {
  const args = process.argv.slice(2);
  if (args[0] === "--") args.shift();
  const { values } = parseArgs({
    args,
    options: { check: { type: "boolean", default: false }, "from-csv": { type: "boolean", default: false } },
  });

  let rows: Row[];
  let links: Link[];
  if (values["from-csv"]) {
    // Offline path: emit straight from the committed sheet. Shares the same
    // normalisation as the importer, so this produces byte-identical output to
    // the DB path as long as the DB was imported from this sheet. Useful before
    // the migrations are applied, and in CI where there are no Supabase creds.
    const parsed = parseIntakeSheet(await readFile(CSV, "utf8"));
    const published = parsed.rows.filter((r) => r.status === "published");
    rows = published as unknown as Row[];
    links = published.flatMap((r) =>
      r.members.map((course_slug, i) => ({ bundle_slug: r.slug, course_slug, position: i })),
    );
  } else {
    const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
    if (!url || !key) {
      throw new Error("catalog:gen needs NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY (or pass --from-csv)");
    }
    // Anon on purpose: this proves the same read the logged-out landing page does.
    const supabase = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
    const { data, error } = await supabase
      .from("course_catalog_public")
      .select(COLUMNS)
      .order("position", { ascending: true });
    if (error) throw new Error(`could not read course_catalog_public as anon: ${error.message}`);
    if (!data?.length) throw new Error("course_catalog_public returned no rows — run catalog:import first");
    rows = data as Row[];

    const { data: linkData, error: linkError } = await supabase
      .from("course_bundle_items_public")
      .select("bundle_slug, course_slug, position")
      .order("position", { ascending: true });
    if (linkError) throw new Error(`could not read course_bundle_items_public as anon: ${linkError.message}`);
    links = (linkData ?? []) as Link[];
  }

  const next = emit(rows, links);
  const rel = relative(process.cwd(), OUT);
  const nCourses = rows.filter((r) => r.kind !== "bundle").length;
  const nBundles = rows.length - nCourses;
  const summary = `${nCourses} courses, ${nBundles} bundles, ${links.length} membership links`;

  if (values.check) {
    const current = await readFile(OUT, "utf8").catch(() => null);
    if (current === next) {
      console.log(`✓ ${rel} is up to date (${summary})`);
      return;
    }
    console.error(`✗ ${rel} is stale — run "pnpm --filter @gm/platform catalog:gen" and commit the result`);
    process.exit(1);
  }

  await writeFile(OUT, next, "utf8");
  console.log(`✓ wrote ${rel} — ${summary}`);
}

main().catch((e) => {
  console.error("catalog gen failed:", e instanceof Error ? e.message : e);
  process.exit(1);
});
